// <auto-generated />
using System;
using ElectrostoreAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace electrostoreAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819144645_AddItemVendorsAndPriceHistory")]
    partial class AddItemVendorsAndPriceHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ElectrostoreAPI.Models.AI", b =>
                {
                    b.Property<int>("id_ia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_ia"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("date_training_ia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description_ia")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name_ia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("trained_ia")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_ia");

                    b.ToTable("AI");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Boxs", b =>
                {
                    b.Property<int>("id_box")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_box"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_store")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("xend_box")
                        .HasColumnType("int");

                    b.Property<int>("xstart_box")
                        .HasColumnType("int");

                    b.Property<int>("yend_box")
                        .HasColumnType("int");

                    b.Property<int>("ystart_box")
                        .HasColumnType("int");

                    b.HasKey("id_box");

                    b.HasIndex("id_store");

                    b.ToTable("Boxs");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.BoxsTags", b =>
                {
                    b.Property<int>("id_box")
                        .HasColumnType("int");

                    b.Property<int>("id_tag")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_box", "id_tag");

                    b.HasIndex("id_tag");

                    b.ToTable("BoxsTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Cameras", b =>
                {
                    b.Property<int>("id_camera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_camera"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("last_seen_camera")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name_camera")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password_camera")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_camera")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("user_camera")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_camera");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Carriers", b =>
                {
                    b.Property<int>("id_carrier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_carrier"));

                    b.Property<int?>("country_carrier")
                        .HasColumnType("int");

                    b.Property<string>("country_iso_carrier")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email_carrier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("key_carrier")
                        .HasColumnType("int");

                    b.Property<string>("name_carrier")
                        .HasColumnType("longtext");

                    b.Property<string>("tel_carrier")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_carrier")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("id_carrier");

                    b.ToTable("Carriers");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Commands", b =>
                {
                    b.Property<int>("id_command")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_command"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("date_command")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("date_delivery_command")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_carrier")
                        .HasColumnType("int");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_tracking_requested")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("is_tracking_validated")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("last_status_command")
                        .HasColumnType("int");

                    b.Property<int?>("last_sub_status_command")
                        .HasColumnType("int");

                    b.Property<float?>("price_command")
                        .HasColumnType("float");

                    b.Property<string>("raw_data_command")
                        .HasColumnType("longtext");

                    b.Property<string>("recipient_address_command")
                        .HasColumnType("longtext");

                    b.Property<string>("shipper_address_command")
                        .HasColumnType("longtext");

                    b.Property<int>("status_command")
                        .HasColumnType("int");

                    b.Property<string>("tracking_number_command")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_command")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("id_command");

                    b.HasIndex("id_carrier");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsComments", b =>
                {
                    b.Property<int>("id_command_comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_command_comment"));

                    b.Property<string>("content_command_comment")
                        .IsRequired()
                        .HasMaxLength(455)
                        .HasColumnType("varchar(455)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_command")
                        .HasColumnType("int");

                    b.Property<int?>("id_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_command_comment");

                    b.HasIndex("id_command");

                    b.HasIndex("id_user");

                    b.ToTable("CommandsComments");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsDocuments", b =>
                {
                    b.Property<int>("id_command_document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_command_document"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_command")
                        .HasColumnType("int");

                    b.Property<string>("name_command_document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("size_command_document")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("type_command_document")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_command_document")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("id_command_document");

                    b.HasIndex("id_command");

                    b.ToTable("CommandsDocuments");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsHistory", b =>
                {
                    b.Property<int>("id_command_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_command_history"));

                    b.Property<string>("city_command_history")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("country_command_history")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description_command_history")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("event_time_utc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_command")
                        .HasColumnType("int");

                    b.Property<string>("latitude_command_history")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("location_command_history")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("longitude_command_history")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("postal_code_command_history")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("stage_command_history")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("state_command_history")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("status_command_history")
                        .HasColumnType("int");

                    b.Property<int?>("sub_status_command_history")
                        .HasMaxLength(150)
                        .HasColumnType("int");

                    b.Property<string>("timezone_command_history")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_command_history");

                    b.HasIndex("id_command");

                    b.ToTable("CommandsHistory");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsItems", b =>
                {
                    b.Property<int>("id_command")
                        .HasColumnType("int");

                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("price_command_item")
                        .HasColumnType("float");

                    b.Property<int>("quantity_command_item")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_command", "id_item");

                    b.HasIndex("id_item");

                    b.ToTable("CommandsItems");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CronJobs", b =>
                {
                    b.Property<int>("id_cronjob")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_cronjob"));

                    b.Property<int>("action_cronjob")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("cron_expression_cronjob")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("is_enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("last_run_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name_cronjob")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("next_run_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("params_cronjob")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_cronjob");

                    b.ToTable("CronJobs");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Imgs", b =>
                {
                    b.Property<int>("id_img")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_img"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description_img")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<string>("name_img")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_picture_img")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("url_thumbnail_img")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("id_img");

                    b.HasIndex("id_item");

                    b.ToTable("Imgs");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemVendorPrices", b =>
                {
                    b.Property<int>("id_item_vendor_price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_item_vendor_price"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("currency_item_vendor_price")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("id_item_vendor")
                        .HasColumnType("int");

                    b.Property<string>("price_breaks_item_vendor_price")
                        .HasColumnType("longtext");

                    b.Property<float>("price_item_vendor_price")
                        .HasColumnType("float");

                    b.Property<int>("quantity_item_vendor_price")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_item_vendor_price");

                    b.HasIndex("id_item_vendor");

                    b.ToTable("ItemVendorPrices");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Items", b =>
                {
                    b.Property<int>("id_item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_item"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description_item")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("friendly_name_item")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("id_img")
                        .HasColumnType("int");

                    b.Property<string>("reference_name_item")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("threshold_min_item")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_item");

                    b.HasIndex("id_img");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsBoxs", b =>
                {
                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<int>("id_box")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("quantity_item_box")
                        .HasColumnType("int");

                    b.Property<int>("threshold_max_item_item_box")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_item", "id_box");

                    b.HasIndex("id_box");

                    b.ToTable("ItemsBoxs");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsDocuments", b =>
                {
                    b.Property<int>("id_item_document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_item_document"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<string>("name_item_document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("size_item_document")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("type_item_document")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_item_document")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("id_item_document");

                    b.HasIndex("id_item");

                    b.ToTable("ItemsDocuments");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsHistory", b =>
                {
                    b.Property<int>("id_item_history")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_item_history"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("id_box")
                        .HasColumnType("int");

                    b.Property<int?>("id_item")
                        .HasColumnType("int");

                    b.Property<int?>("id_user")
                        .HasColumnType("int");

                    b.Property<int?>("new_quantity_item_history")
                        .HasColumnType("int");

                    b.Property<string>("notes_item_history")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("old_quantity_item_history")
                        .HasColumnType("int");

                    b.Property<int?>("quantity_change_item_history")
                        .HasColumnType("int");

                    b.Property<int>("type_item_history")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_item_history");

                    b.HasIndex("id_box");

                    b.HasIndex("id_item");

                    b.HasIndex("id_user");

                    b.ToTable("ItemsHistory");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsTags", b =>
                {
                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<int>("id_tag")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_item", "id_tag");

                    b.HasIndex("id_tag");

                    b.ToTable("ItemsTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsVendors", b =>
                {
                    b.Property<int>("id_item_vendor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_item_vendor"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_item_vendor")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<string>("vendor_sku_item_vendor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("vendor_type_item_vendor")
                        .HasColumnType("int");

                    b.HasKey("id_item_vendor");

                    b.HasIndex("id_item");

                    b.ToTable("ItemsVendors");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.JwiAccessTokens", b =>
                {
                    b.Property<Guid>("id_jwi_access")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("auth_method_jwi_access")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by_ip_jwi_access")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("revoked_by_ip_jwi_access")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("revoked_reason_jwi_access")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("session_id_jwi_access")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_jwi_access");

                    b.HasIndex("id_user");

                    b.ToTable("JwiAccessTokens");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.JwiRefreshTokens", b =>
                {
                    b.Property<Guid>("id_jwi_refresh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("auth_method_jwi_refresh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("created_by_ip_jwi_refresh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("id_jwi_access")
                        .HasColumnType("char(36)");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<bool>("is_revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("revoked_by_ip_jwi_refresh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("revoked_reason_jwi_refresh")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("session_id_jwi_refresh")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_jwi_refresh");

                    b.HasIndex("id_jwi_access");

                    b.HasIndex("id_user");

                    b.ToTable("JwiRefreshTokens");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Leds", b =>
                {
                    b.Property<int>("id_led")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_led"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_store")
                        .HasColumnType("int");

                    b.Property<int>("mqtt_id_led")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("x_led")
                        .HasColumnType("int");

                    b.Property<int>("y_led")
                        .HasColumnType("int");

                    b.HasKey("id_led");

                    b.HasIndex("id_store");

                    b.ToTable("Leds");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectTags", b =>
                {
                    b.Property<int>("id_project_tag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_project_tag"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name_project_tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("weight_project_tag")
                        .HasColumnType("int");

                    b.HasKey("id_project_tag");

                    b.ToTable("ProjectTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Projects", b =>
                {
                    b.Property<int>("id_project")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_project"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description_project")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("name_project")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("status_project")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_project")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("id_project");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsComments", b =>
                {
                    b.Property<int>("id_project_comment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_project_comment"));

                    b.Property<string>("content_project_comment")
                        .IsRequired()
                        .HasMaxLength(455)
                        .HasColumnType("varchar(455)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_project")
                        .HasColumnType("int");

                    b.Property<int?>("id_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_project_comment");

                    b.HasIndex("id_project");

                    b.HasIndex("id_user");

                    b.ToTable("ProjectsComments");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsDocuments", b =>
                {
                    b.Property<int>("id_project_document")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_project_document"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_project")
                        .HasColumnType("int");

                    b.Property<string>("name_project_document")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("size_project_document")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("type_project_document")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("url_project_document")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("id_project_document");

                    b.HasIndex("id_project");

                    b.ToTable("ProjectsDocuments");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsItems", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int");

                    b.Property<int>("id_item")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("quantity_project_item")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_project", "id_item");

                    b.HasIndex("id_item");

                    b.ToTable("ProjectsItems");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsProjectTags", b =>
                {
                    b.Property<int>("id_project")
                        .HasColumnType("int");

                    b.Property<int>("id_project_tag")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_project", "id_project_tag");

                    b.HasIndex("id_project_tag");

                    b.ToTable("ProjectsProjectTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsStatus", b =>
                {
                    b.Property<int>("id_project_status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_project_status"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_project")
                        .HasColumnType("int");

                    b.Property<int>("status_project")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_project_status");

                    b.HasIndex("id_project");

                    b.ToTable("ProjectsStatus");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Stores", b =>
                {
                    b.Property<int>("id_store")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_store"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_mqtt_connected_store")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("mqtt_last_seen_store")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("mqtt_name_store")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("mqtt_password_encryption_iv_store")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("mqtt_password_encryption_tag_store")
                        .IsRequired()
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("mqtt_password_store")
                        .IsRequired()
                        .HasColumnType("varbinary(512)");

                    b.Property<string>("name_store")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("xlength_store")
                        .HasColumnType("int");

                    b.Property<int>("ylength_store")
                        .HasColumnType("int");

                    b.HasKey("id_store");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.StoresTags", b =>
                {
                    b.Property<int>("id_store")
                        .HasColumnType("int");

                    b.Property<int>("id_tag")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_store", "id_tag");

                    b.HasIndex("id_tag");

                    b.ToTable("StoresTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Tags", b =>
                {
                    b.Property<int>("id_tag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_tag"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name_tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("weight_tag")
                        .HasColumnType("int");

                    b.HasKey("id_tag");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.UserPushSubscriptions", b =>
                {
                    b.Property<int>("id_user_push_subscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_user_push_subscription"));

                    b.Property<string>("auth")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("device_name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<string>("p256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_user_push_subscription");

                    b.HasIndex("id_user");

                    b.ToTable("UserPushSubscriptions");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Users", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_user"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email_user")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("firstname_user")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("name_user")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password_user")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("reset_token")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("reset_token_expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("role_user")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id_user");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Boxs", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Stores", "Store")
                        .WithMany("Boxs")
                        .HasForeignKey("id_store")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.BoxsTags", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Boxs", "Box")
                        .WithMany("BoxsTags")
                        .HasForeignKey("id_box")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Tags", "Tag")
                        .WithMany("BoxsTags")
                        .HasForeignKey("id_tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Commands", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Carriers", "Carrier")
                        .WithMany()
                        .HasForeignKey("id_carrier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsComments", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Commands", "Command")
                        .WithMany("CommandsComments")
                        .HasForeignKey("id_command")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Users", "User")
                        .WithMany("CommandsComments")
                        .HasForeignKey("id_user");

                    b.Navigation("Command");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsDocuments", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Commands", "Command")
                        .WithMany("CommandsDocuments")
                        .HasForeignKey("id_command")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsHistory", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Commands", "command")
                        .WithMany("CommandsHistory")
                        .HasForeignKey("id_command")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("command");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.CommandsItems", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Commands", "Command")
                        .WithMany("CommandsItems")
                        .HasForeignKey("id_command")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("CommandsItems")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Command");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Imgs", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany()
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemVendorPrices", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.ItemsVendors", "ItemVendor")
                        .WithMany("ItemVendorPrices")
                        .HasForeignKey("id_item_vendor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemVendor");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Items", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Imgs", "Img")
                        .WithMany()
                        .HasForeignKey("id_img");

                    b.Navigation("Img");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsBoxs", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Boxs", "Box")
                        .WithMany("ItemsBoxs")
                        .HasForeignKey("id_box")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("ItemsBoxs")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsDocuments", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("ItemsDocuments")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsHistory", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Boxs", "Box")
                        .WithMany()
                        .HasForeignKey("id_box")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("ItemsHistory")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ElectrostoreAPI.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Box");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsTags", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("ItemsTags")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Tags", "Tag")
                        .WithMany("ItemsTags")
                        .HasForeignKey("id_tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsVendors", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("ItemsVendors")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.JwiAccessTokens", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.JwiRefreshTokens", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.JwiAccessTokens", "JWIAccessToken")
                        .WithMany()
                        .HasForeignKey("id_jwi_access")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JWIAccessToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Leds", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Stores", "Store")
                        .WithMany("Leds")
                        .HasForeignKey("id_store")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsComments", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Projects", "Project")
                        .WithMany("ProjectsComments")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Users", "User")
                        .WithMany("ProjectsComments")
                        .HasForeignKey("id_user");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsDocuments", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Projects", "Project")
                        .WithMany("ProjectsDocuments")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsItems", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Items", "Item")
                        .WithMany("ProjectsItems")
                        .HasForeignKey("id_item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Projects", "Project")
                        .WithMany("ProjectsItems")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsProjectTags", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Projects", "Project")
                        .WithMany("ProjectsProjectTags")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.ProjectTags", "ProjectTag")
                        .WithMany("ProjectsProjectTags")
                        .HasForeignKey("id_project_tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ProjectTag");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectsStatus", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Projects", "Project")
                        .WithMany("ProjectsStatus")
                        .HasForeignKey("id_project")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.StoresTags", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Stores", "Store")
                        .WithMany("StoresTags")
                        .HasForeignKey("id_store")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectrostoreAPI.Models.Tags", "Tag")
                        .WithMany("StoresTags")
                        .HasForeignKey("id_tag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.UserPushSubscriptions", b =>
                {
                    b.HasOne("ElectrostoreAPI.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Boxs", b =>
                {
                    b.Navigation("BoxsTags");

                    b.Navigation("ItemsBoxs");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Commands", b =>
                {
                    b.Navigation("CommandsComments");

                    b.Navigation("CommandsDocuments");

                    b.Navigation("CommandsHistory");

                    b.Navigation("CommandsItems");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Items", b =>
                {
                    b.Navigation("CommandsItems");

                    b.Navigation("ItemsBoxs");

                    b.Navigation("ItemsDocuments");

                    b.Navigation("ItemsHistory");

                    b.Navigation("ItemsTags");

                    b.Navigation("ItemsVendors");

                    b.Navigation("ProjectsItems");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ItemsVendors", b =>
                {
                    b.Navigation("ItemVendorPrices");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.ProjectTags", b =>
                {
                    b.Navigation("ProjectsProjectTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Projects", b =>
                {
                    b.Navigation("ProjectsComments");

                    b.Navigation("ProjectsDocuments");

                    b.Navigation("ProjectsItems");

                    b.Navigation("ProjectsProjectTags");

                    b.Navigation("ProjectsStatus");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Stores", b =>
                {
                    b.Navigation("Boxs");

                    b.Navigation("Leds");

                    b.Navigation("StoresTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Tags", b =>
                {
                    b.Navigation("BoxsTags");

                    b.Navigation("ItemsTags");

                    b.Navigation("StoresTags");
                });

            modelBuilder.Entity("ElectrostoreAPI.Models.Users", b =>
                {
                    b.Navigation("CommandsComments");

                    b.Navigation("ProjectsComments");
                });
#pragma warning restore 612, 618
        }
    }
}
