version: '3'

services:
  electrostoreapi:
    build: electrostoreAPI/.
    container_name: electrostoreapi
    restart: always
    networks:
      - electrostorenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.electrostoreAPI.rule=Host(`yourDNSforAPI.net`)"
      - "traefik.http.routers.electrostoreAPI.entrypoints=websecure"
      - "traefik.http.routers.electrostoreAPI.tls=true"
      - "traefik.http.routers.electrostoreAPI.tls.certresolver=myresolver"
      - "traefik.http.services.electrostoreAPI.loadbalancer.server.port=80"
    volumes:
      - electrostoreDATA:/app/wwwroot
  electrostoreia:
    build: electrostoreIA/.
    container_name: electrostoreia
    restart: always
    networks:
      - electrostorenet
    labels:
      - "traefik.enable=false"
    depends_on:
      - electrostoreapi
    volumes:
      - electrostoreDATA:/data
    cpus: 1 # limit the cpu usage for exec this container in a raspberry pi
  electrostorefront:
    build: electrostoreFRONT/.
    container_name: electrostorefront
    restart: always
    networks:
      - electrostorenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.electrostoreFRONT.rule=Host(`yourDNSforFRONT.net`)"
      - "traefik.http.routers.electrostoreFRONT.entrypoints=websecure"
      - "traefik.http.routers.electrostoreFRONT.tls=true"
      - "traefik.http.routers.electrostoreFRONT.tls.certresolver=myresolver"
      - "traefik.http.services.electrostoreFRONT.loadbalancer.server.port=80"
    depends_on:
      - electrostoreapi

networks:
  electrostorenet:
    name: electrostorenet

volumes:
  electrostoreDATA:
    name: electrostoreDATA