; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

; ─── General settings ────────────────────────────────────────────────────────
[env]
upload_speed = 115200
upload_port = COM6
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
    bblanchon/ArduinoJson @ ^6.21.5

; ─── ESP32 ────────────────────────────────────────────────────────────────────
[env:esp32]
platform = espressif32 @ ^6.9.0
board = esp32dev
lib_deps =
    ${env.lib_deps}
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.3

; ─── ESP32 OTA ────────────────────────────────────────────────────────────────
[env:esp32_ota]
extends = env:esp32
upload_protocol = espota
upload_port = 192.168.1.101  ; Replace with your ESP's IP address
upload_flags =
    --port=8100
    --auth=0  ; Replace with your configured password, or use "0" if none
