; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

; ─── General settings ────────────────────────────────────────────────────────
[env]
upload_speed = 115200
upload_port = COM6
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
    bblanchon/ArduinoJson @ ^6.21.5

; ─── ESP32 ────────────────────────────────────────────────────────────────────
[env:esp32]
platform = espressif32 @ ^6.9.0
board = esp32dev
lib_deps =
    ${env.lib_deps}
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
