; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

; ─── General settings ────────────────────────────────────────────────────────
[env]
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3
    bblanchon/ArduinoJson @ ^6.21.5
    ESP32Async/ESPAsyncWebServer @ 3.6.0
    ESP32Async/AsyncTCP @ ^3.4.10

; ─── ESP32 ────────────────────────────────────────────────────────────────────
[env:esp32]
upload_speed = 921600
monitor_speed = 115200
upload_port = COM3
platform = espressif32 @ ^6.9.0
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = esp32_partition.csv
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram = enable

; ─── ESP32 OTA ────────────────────────────────────────────────────────────────
[env:esp32_ota]
extends = env:esp32
upload_protocol = espota
upload_port = 192.168.1.101  ; Replace with your ESP's IP address
upload_flags =
    --port=8100
    --auth=electostore  ; Replace with your configured password, or use "electostore" if none
