
const TrackingSubStatus = {
	NotFound_Other: 0,
	NotFound_InvalidCode: 1,
	InfoReceived: 2,
	InTransit_PickedUp: 3,
	InTransit_Other: 4,
	InTransit_Departure: 5,
	InTransit_Arrival: 6,
	InTransit_CustomsProcessing: 7,
	InTransit_CustomsReleased: 8,
	InTransit_CustomsRequiringInformation: 9,
	Expired_Other: 10,
	AvailableForPickup_Other: 11,
	OutForDelivery_Other: 12,
	DeliveryFailure_Other: 13,
	DeliveryFailure_NoBody: 14,
	DeliveryFailure_Security: 15,
	DeliveryFailure_Rejected: 16,
	DeliveryFailure_InvalidAddress: 17,
	Delivered_Other: 18,
	Exception_Other: 19,
	Exception_Returning: 20,
	Exception_Returned: 21,
	Exception_NoBody: 22,
	Exception_Security: 23,
	Exception_Damage: 24,
	Exception_Rejected: 25,
	Exception_Delayed: 26,
	Exception_Lost: 27,
	Exception_Destroyed: 28,
	Exception_Cancel: 29,
};

export default TrackingSubStatus;