; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

; ─── General settings ────────────────────────────────────────────────────────
[env]
framework = arduino
lib_deps =
    knolleary/PubSubClient @ ^2.8.0
    adafruit/Adafruit NeoPixel @ ^1.12.3
    bblanchon/ArduinoJson @ ^6.21.5
    ESP32Async/ESPAsyncWebServer @ 3.6.0

; ─── ESP32 ────────────────────────────────────────────────────────────────────
[env:esp32]
upload_speed = 921600
monitor_speed = 115200
upload_port = COM3
platform = espressif32 @ ^6.9.0
board = esp32dev
board_build.filesystem = littlefs
board_build.partitions = esp32_partition.csv
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.psram = disable
lib_deps =
    ${env.lib_deps}
    ESP32Async/AsyncTCP @ ^3.4.10

; ─── ESP8266 ──────────────────────────────────────────────────────────────────
[env:esp8266]
upload_speed = 115200
monitor_speed = 115200
upload_port = COM4
platform = espressif8266 @ ^4.2.1
board = esp12e
board_build.mcu = esp8266
board_build.f_cpu = 80000000L
board_build.flash_mode = dout
board_build.flash_size = 1M64
board_build.flash_freq = 40m
board_build.upload_speed = 115200
board_build.reset_method = dtr
board_build.lwip_variant = v2_low_memory
board_build.led = 2
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.1m64.ld
board_build.partitions = default
board_build.nonos_sdk_version = 190703
lib_deps =
    ${env.lib_deps}
    ESP32Async/ESPAsyncTCP @ ^2.0.0

; ─── ESP8266 OTA ──────────────────────────────────────────────────────────────
[env:esp8266_ota]
extends = env:esp8266
upload_protocol = espota
upload_port = 192.168.1.100  ; Replace with your ESP's IP address
upload_flags =
    --port=8100
    --auth=electostore  ; Replace with your configured password, or use "electostore" if none
lib_deps =
    ${env.lib_deps}
    ESP32Async/ESPAsyncTCP @ ^2.0.0

; ─── ESP32 OTA ────────────────────────────────────────────────────────────────
[env:esp32_ota]
extends = env:esp32
upload_protocol = espota
upload_port = 192.168.1.101  ; Replace with your ESP's IP address
upload_flags =
    --port=8100
    --auth=electostore  ; Replace with your configured password, or use "electostore" if none
lib_deps =
    ${env.lib_deps}
    ESP32Async/AsyncTCP @ ^3.4.10
