name: tests PR IA

on:
  pull_request:
    paths:
      - "electrostoreIA/**"
      - "tests/electrostoreIA/**"

jobs:
  test-IA:
    name: tests - IA
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./electrostoreIA
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r ../tests/electrostoreIA/requirements.txt
    - name: Run tests with coverage
      run: |
        python -m pytest ../tests/electrostoreIA --cov=electrostoreIA --cov-report=xml:coverage.xml
    - name: Get PR ID
      id: get-pr-id
      run: |
        PR_ID="${{ github.event.pull_request.number }}"
        echo "pr_id=$PR_ID" >> $GITHUB_OUTPUT
    - name: SonarScanner
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=PR-${{ steps.get-pr-id.outputs.pr_id }}-electrostore-ia
          -Dsonar.projectName=PR-${{ steps.get-pr-id.outputs.pr_id }}-electrostore-ia
          -Dsonar.sources=electrostoreIA
          -Dsonar.python.coverage.reportPaths=electrostoreIA/coverage.xml
          -Dsonar.cfamily.cache.enabled=false
