name: tests PR FRONT

on:
  pull_request:
    paths:
      - "electrostoreFRONT/**"
      - "tests/electrostoreFRONT/**"

jobs:
  test-front:
    name: tests - FRONT
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./electrostoreFRONT
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Install test dependencies
      run: cd ../tests/electrostoreFRONT && npm install
    - name: Run unit tests with coverage
      run: cd ../tests/electrostoreFRONT && npm run test:unit -- --coverage --coverage.reporter=lcov
    - name: Cypress run
      env:
        VITE_API_URL: http://localhost/vite_api_url_placeholder/api
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        wait-on-timeout: 30
        working-directory: ./tests/electrostoreFRONT
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: tests/electrostoreFRONT/cypress/screenshots
    - name: Get PR ID
      id: get-pr-id
      run: |
        PR_ID="${{ github.event.pull_request.number }}"
        echo "pr_id=$PR_ID" >> $GITHUB_OUTPUT
    - name: SonarScanner
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=PR-${{ steps.get-pr-id.outputs.pr_id }}-electrostore-front
          -Dsonar.projectName=PR-${{ steps.get-pr-id.outputs.pr_id }}-electrostore-front
          -Dsonar.sources=electrostoreFRONT
          -Dsonar.javascript.lcov.reportPaths=tests/electrostoreFRONT/coverage/lcov.info
          -Dsonar.cfamily.cache.enabled=false
