name: test

on:
  pull_request:
    paths:
      - "electrostoreFRONT/**"
      - "tests/electrostoreFRONT/**"

jobs:
  test-front:
    name: tests - FRONT
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./electrostoreFRONT
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Install test dependencies
      run: cd ../tests/electrostoreFRONT && npm install
    - name: Run unit tests with coverage
      run: cd ../tests/electrostoreFRONT && npm run test:unit -- --coverage --coverage.reporter=lcov
    - name: Upload front coverage
      uses: actions/upload-artifact@v4
      with:
        name: front-coverage
        path: tests/electrostoreFRONT/coverage
    - name: Cypress run
      env:
        VITE_API_URL: http://localhost/vite_api_url_placeholder/api
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        wait-on-timeout: 30
        working-directory: ./tests/electrostoreFRONT
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: tests/electrostoreFRONT/cypress/screenshots

  sonarqube-front:
    name: SonarQube - FRONT
    needs:
      - test-front
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - name: Download FRONT coverage
      uses: actions/download-artifact@v4
      with:
        name: front-coverage
        path: front-coverage
    - name: SonarScanner
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=electrostore-front
          -Dsonar.projectName=electrostore-front
          -Dsonar.sources=electrostoreFRONT
          -Dsonar.javascript.lcov.reportPaths=front-coverage/lcov.info
          -Dsonar.cfamily.cache.enabled=false
