name: Release

on:
  workflow_call:
    inputs:
      version:
        description: 'the tag/branch to release.'
        required: true
        type: string
      branch:
        description: 'the branch or tag that triggered this workflow.'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      version:
        description: 'the tag/branch to release.'
        required: true
        type: string
      branch:
        description: 'the branch or tag that triggered this workflow.'
        required: true
        type: string

permissions:
  issues: read
  contents: write
  packages: read
  pull-requests: read
  deployments: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Get previous tag
        id: previous_tag
        shell: bash
        run: |
          git fetch --tags --force
          previous_tag=$(git tag --list 'v*.*.*' --sort=-v:refname \
            | grep -v -x "${{ inputs.version }}" \
            | head -n 1)
          if [ -z "$previous_tag" ]; then
            echo "previous_tag=none" >> $GITHUB_OUTPUT
          else
            echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT
          fi
          echo "current tag: ${{ inputs.version }} / previous tag: $previous_tag"

      - name: Generate Changelog
        if: ${{ steps.previous_tag.outputs.previous_tag != 'none' }}
        uses: metcalfc/changelog-generator@v4.7.0
        id: changelog
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{ inputs.version }}
          base-ref: ${{ steps.previous_tag.outputs.previous_tag }}

      - name: Show changelog
        if: ${{ steps.changelog.outputs.changelog != '' }}
        run: |
          cat << "EOF"
          ${{ steps.changelog.outputs.changelog }}
          EOF

      - name: Create First Release
        if: ${{ steps.previous_tag.outputs.previous_tag == 'none' }}
        uses: ncipollo/release-action@v1.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ github.token }}
          body: "Première release : ${{ inputs.version }}."
          draft: false
          prerelease: false
          generateReleaseNotes: true
          tag: ${{ inputs.version }}
          name: Release ${{ inputs.version }}

      - name: Create Release with Changelog
        if: ${{ steps.previous_tag.outputs.previous_tag != 'none' }}
        uses: ncipollo/release-action@v1.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          generateReleaseNotes: true
          tag: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
