name: test

on:
  workflow_call:
    inputs:
      branch:
        description: 'The branch that triggered this workflow.'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch that triggered this workflow.'
        required: true
        type: string

jobs:
  test-api:
    name: tests - API
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./electrostoreAPI
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - name: Set up C#
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test ../tests/electrostoreAPI

  test-front:
    name: tests - FRONT
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./electrostoreFRONT
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Install test dependencies
      run: cd ../tests/electrostoreFRONT && npm install
    - name: Run unit tests
      run: cd ../tests/electrostoreFRONT && npm run test:unit
    - name: Cypress run
      env:
        VITE_API_URL: http://localhost:8080
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: 'http://localhost:5173'
        wait-on-timeout: 30
        working-directory: ./tests/electrostoreFRONT

  test-IA:
    name: tests - IA
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./electrostoreIA
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r ../tests/electrostoreIA/requirements.txt
    - name: Run tests
      run: |
        python -m pytest ../tests/electrostoreIA
